### ISSUE TITLE
Crashes.

### ISSUE THREAD

**Issue by xLumi** [DxxxxY/SplashHelper#1]
After adding information to the fields, clicking done causes game crashes, and crashes when trying to join Hypixel.
[crash-2020-08-27_14.33.46-client.txt](https://github.com/DxxxxY/SplashHelper/files/5144188/crash-2020-08-27_14.33.46-client.txt)

**Comment by dxxxxy** [comment]
I can see that you're using Labymod. It is highly discouraged to use it since it is not compatible with a lot of mods.
[https://www.labymod.net/idea/1567](https://www.labymod.net/idea/1567)
and
[https://www.labymod.net/idea/1969](https://www.labymod.net/idea/1969)
are both examples of incompatibility.
